import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
  fab: {
    position: 'fixed',
    bottom: theme.spacing(4),
    right: theme.spacing(4),
    zIndex: 1000,
    backgroundColor: '#2196F3',
    color: 'white',
    '&:hover': {
      backgroundColor: '#1976D2',
    },
  },
  chatWindow: {
    position: 'fixed',
    bottom: theme.spacing(12),
    right: theme.spacing(4),
    width: 380,
    height: 550,
    zIndex: 1000,
    display: 'flex',
    flexDirection: 'column',
    borderRadius: 16,
    overflow: 'hidden',
    boxShadow: '0 8px 32px rgba(0,0,0,0.15)',
    transition: 'transform 0.3s ease-in-out, opacity 0.3s ease-in-out',
  },
  header: {
    backgroundColor: '#2196F3',
    color: 'white',
    padding: theme.spacing(2),
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    zIndex: 1,
  },
  messagesContainer: {
    flex: 1,
    padding: theme.spacing(2),
    overflowY: 'auto',
    backgroundColor: '#f8f9fa',
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(2),
  },
  messageBubble: {
    padding: theme.spacing(1.5, 2),
    borderRadius: 18,
    maxWidth: '85%',
    wordBreak: 'break-word',
    fontSize: '0.95rem',
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap', // Preserves formatting from AI
  },
  userMessage: {
    backgroundColor: '#2196F3',
    color: 'white',
    alignSelf: 'flex-end',
    borderBottomRightRadius: 4,
    boxShadow: '0 2px 4px rgba(33, 150, 243, 0.3)',
  },
  aiMessage: {
    backgroundColor: 'white',
    color: '#333',
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 4,
    boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
    border: '1px solid #eee',
  },
  inputArea: {
    display: 'flex',
    padding: theme.spacing(1.5, 2),
    backgroundColor: 'white',
    borderTop: '1px solid #eee',
    alignItems: 'center',
  },
  inputBase: {
    flex: 1,
    marginRight: theme.spacing(1),
    padding: theme.spacing(1, 2),
    backgroundColor: '#f0f2f5',
    borderRadius: 24,
    fontSize: '0.95rem',
    color: '#333',
  },
  sendButton: {
    color: '#2196F3',
    padding: 8,
    flexShrink: 0,
  },
  actionButton: {
    flexShrink: 0,
  },
  loadingContainer: {
    alignSelf: 'flex-start',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: theme.spacing(1, 2),
    backgroundColor: 'white',
    borderRadius: 18,
    borderBottomLeftRadius: 4,
    boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
    border: '1px solid #eee',
  },
  dot: {
    width: 6,
    height: 6,
    backgroundColor: '#2196F3',
    borderRadius: '50%',
    animation: '$bounce 1.4s infinite ease-in-out both',
  },
  dot1: { animationDelay: '-0.32s' },
  dot2: { animationDelay: '-0.16s' },
  '@keyframes bounce': {
    '0%, 80%, 100%': { transform: 'scale(0)' },
    '40%': { transform: 'scale(1)' },
  },
  imagePreviewContainer: {
    position: 'absolute',
    bottom: '100%',
    left: theme.spacing(2),
    marginBottom: theme.spacing(1),
    display: 'inline-block',
  },
  imagePreview: {
    height: 80,
    width: 80,
    objectFit: 'cover',
    borderRadius: 8,
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
    border: '2px solid white',
  },
  removeImageButton: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#ff4d4d',
    color: 'white',
    padding: 4,
    '&:hover': {
      backgroundColor: '#ff3333',
    },
  },
}));
